PUT http://localhost:3001/clients/5f661321da3f401bbff4e3ce HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjY2MGJjOGM1NWVlNzEzNWUzOGQ0OGUiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE2MDA1MjQxNzB9.z7ssI10qHzpgUPHym3MTSlHrWVLdRPJ2QDckam9aqZY

{
    "firstname": "boom",
    "lastname": "fdsea",
    "phone": "0693614508",
    "geographicSector": "north",
    "displayName": "test boom",
    "address": "chemin carbon"
}



